#
# © 2026-present https://github.com/cengiz-pz
#

name: Gradle Kotlin DSL Style

on:
  pull_request:
    branches:
      - main
    paths:
      - '**/*.gradle.kts'

jobs:
  gradle-kts-style:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install Node
        uses: ./.github/actions/install-node

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 17

      - name: Install ktlint
        uses: ./.github/actions/install-ktlint
        with:
          version: '1.8.0'

      - name: Run ktlint on Gradle Kotlin DSL files
        run: ktlint "addon/*.gradle.kts" "android/*.gradle.kts" "common/*.gradle.kts"

      - name: Install editorconfig-checker
        uses: ./.github/actions/install-ec
        with:
          version: '3.6.1'

      - name: Verify EditorConfig (Final Newline & Trailing Space)
        run: find addon android common -maxdepth 1 -name "*.gradle.kts" | xargs editorconfig-checker
