#
# © 2026-present https://github.com/cengiz-pz
#

name: Sync Labels

on:
  push:
    branches:
      - main
    paths:
      - '.github/config/labels.yml'

permissions:
  issues: write

jobs:
  labels:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          sparse-checkout: .github/config/labels.yml

      - name: Label Sync 
        uses: EndBug/label-sync@v2
        with:
          config-file: .github/config/labels.yml
          delete-other-labels: true
          token: ${{ secrets.GITHUB_TOKEN }}
