#
# © 2026-present https://github.com/cengiz-pz
#

name: Properties File Style

on:
  pull_request:
    branches:
      - main
    paths:
      - 'common/config/*.properties'
      - 'ios/config/*.properties'

jobs:
  properties-style:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install editorconfig-checker
        uses: ./.github/actions/install-ec

      - name: Validate properties formatting
        run: editorconfig-checker common/config/*.properties ios/config/*.properties
